/**
* This code was generated by v0 by Vercel.
* @see https://v0.dev/t/A8ZhQeV8qNU
* Documentation: https://v0.dev/docs#integrating-generated-code-into-your-nextjs-app
*/

/** Add fonts into your Next.js project:

import { Inter } from 'next/font/google'

inter({
  subsets: ['latin'],
  display: 'swap',
})

To read more about using these font, please visit the Next.js documentation:
- App Directory: https://nextjs.org/docs/app/building-your-application/optimizing/fonts
- Pages Directory: https://nextjs.org/docs/pages/building-your-application/optimizing/fonts
**/
import { Card, CardHeader, CardTitle, CardDescription, CardContent, CardFooter } from "@/components/ui/card"
import { Textarea } from "@/components/ui/textarea"
import { Button } from "@/components/ui/button"

export function CommentForm() {
  const handleSubmit = () => {
    return (e: React.FormEvent<HTMLFormElement>) => {
      e.preventDefault()
      console.log('submit')
    }
  }
  return (
    <div className="space-y-4">
      <form onSubmit={handleSubmit()}>
      <div className="space-y-2">
        <h3 className="text-2xl font-bold">Laissez un commentaire</h3>
        <p className="text-muted-foreground">Partagez vos pensées et vos réflexions avec nous.</p>
      </div>
      <div className="space-y-2">
        <Textarea placeholder="Écrivez votre commentaire ici..." className="min-h-[120px]" />
        <Button>Envoyer</Button>
      </div>
      </form>
    </div>
  )
}
