"use client";
/**
 * This code was generated by v0 by Vercel.
 * @see https://v0.dev/t/A8ZhQeV8qNU
 * Documentation: https://v0.dev/docs#integrating-generated-code-into-your-nextjs-app
 */

/** Add fonts into your Next.js project:

import { Inter } from 'next/font/google'

inter({
  subsets: ['latin'],
  display: 'swap',
})

To read more about using these font, please visit the Next.js documentation:
- App Directory: https://nextjs.org/docs/app/building-your-application/optimizing/fonts
- Pages Directory: https://nextjs.org/docs/pages/building-your-application/optimizing/fonts
**/
import {
  Card,
  CardHeader,
  CardTitle,
  CardDescription,
  CardContent,
  CardFooter,
} from "@/components/ui/card";
import { Textarea } from "@/components/ui/textarea";
import { Button } from "@/components/ui/button";
import { useState } from "react";
import { useMutation } from "@tanstack/react-query";
import axios from "axios";

export function CommentForm() {
  const [comment, setComment] = useState("");

  const mutation = useMutation({
    mutationFn: async (newTodo) => {
      await axios.post("http://localhost:3000/api/party", newTodo);
    },
  });
  async function onSubmit() {
    console.log(comment);

    const dataForm = {
      comment: comment,
    };

    mutation.mutate(dataForm);

    if (mutation.isLoading) {
      return <span>Updating...</span>;
    }
  }
  return (
    <div className="space-y-4">
      <form onSubmit={onSubmit}>
        <div className="space-y-2">
          <h3 className="text-2xl font-bold">Laissez un commentaire</h3>
          <p className="text-muted-foreground">
            Partagez vos pensées et vos réflexions avec nous.
          </p>
        </div>
        <div className="space-y-2">
          <Textarea
            onChange={(e) => setComment(e.target.value)}
            placeholder="Écrivez votre commentaire ici..."
            className="min-h-[120px]"
          />
          <Button type="submit">Envoyer</Button>
        </div>
      </form>
    </div>
  );
}
